config/routes.rb
Erp::Application.routes.draw do
  devise_for :users
  resources :pessoas

  root 'pessoas#index'

end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pessoa }
      else
        format.html { render action: 'new' }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :data_nascimento, :ativo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Erp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="margin: 15px;">
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <a class="brand" href="#">
          <img src="http://rubyonrails.org/images/rails.png" alt="Rails" width="25" height="25">
        </a>
        <ul class="nav">
          <li><a href="#">Home</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
        <% unless user_signed_in? %>
            <%= link_to "Entrar", 'http://localhost:3000/users/sign_in', :class => "brand pull-right" %>
        <% else %>
            <%= link_to "Sair", destroy_user_session_path, :method => :delete, :class => "brand pull-right" %>
        <% end %>
      </div>
    </div>

    <%= yield %>

    <footer>
      <hr/>
      <div class="row">
        <div class="span1">
          <p>Em Desenvolvimento</p>
        </div>
        <div class="span9 offset9">
          <% if user_signed_in? %>
              <p>Usuario: <%= current_user.email %></p>
          <% end %>
        </div>
      </div>
    </footer>

</body>
</html>

app/views/pessoas/_form.html.erb
<%= simple_form_for(@pessoa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :data_nascimento %>
    <%= f.input :ativo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa, :class => "btn" %> |
<%= link_to 'Back', pessoas_path, :class => "btn" %>

app/views/pessoas/index.html.erb
<h1>Listing pessoas</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data nascimento</th>
      <th>Ativo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody class="table table-condensed">
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.data_nascimento %></td>
        <td><%= pessoa.ativo %></td>
        <td><%= link_to 'Show', pessoa, :class => "btn btn-mini" %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa), :class => "btn btn-mini" %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path, :class => 'btn btn-primary' %>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path, :class => "btn" %>

app/views/pessoas/show.html.erb
<p class="notice" id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @pessoa.data_nascimento %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @pessoa.ativo %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa), :class => "btn" %> |
<%= link_to 'Back', pessoas_path, :class => "btn" %>